[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
storage_app = "BnDUouxaJCFAeKjdHY53NCCXQBw64yHeTcfuM3Y2d6Dn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/morteza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
